web/router.ex
defmodule Unu.Router do
  use Unu.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Unu.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  scope "/", Unu do
    pipe_through :browser

    get  "/", TalentController, :landing_page
    # get  "/", PageController, :landing_page

    get  "/talent/signup", TalentController, :signup_page
    post "/talent/signup", TalentController, :signup_post
    get  "/talent/:id", TalentController, :show_page
    get  "/talent/:id/edit_profile", TalentController, :edit_profile_page
    post "/talent/:id", TalentController, :edit_post

    get  "/login", SessionController, :login_page
    post "/login", SessionController, :login
    post "/logout", SessionController, :logout

    get  "/talent", PageController, :talent_search

    # For interactive testing only:
    get "/users", UserController, :index_page
    delete "/users/:id", UserController, :delete
  end

  # Other scopes may use custom stacks.
  scope "/api", Unu do
    pipe_through :api

    post "/talent/:id/upload_headshot", TalentController, :upload_headshot_post
  end
end

web/views/layout_view.ex
defmodule Unu.LayoutView do
  use Unu.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns:"http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Language" content="en">
    <meta name="google-site-verification" content="ClBh2WH0Zx_Cf8ixkCb67Oe2r5zaAcTKj9uLe39MWtw" />
    <meta name="google" content="notranslate">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>UNU</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header>
	<!-- <h1>UNU</h1> -->
	<nav class="navbar navbar-default" role="navigation">
	  <div class="navbar-header">
	    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	      <span class="sr-only">Menu</span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	      <span class="icon-bar"></span>
	    </button>
	    <a class="navbar-brand" href="/">UNU</a>
	  </div> <!-- .navbar-header -->
	  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    <ul class="nav navbar-nav navbar-right">
	      <%= if @current_user do %>
	      <p class="navbar-text"><%= "Hi, " <> @current_user.first_name %></p>
	      <!-- <li class="dropdown"> -->
	      <!--   <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= "Hi, " <> @current_user.first_name %> <span class="caret"></span></a> -->
	      <!--   <ul class="dropdown-menu"> -->
	      <li><%= button "My profile", to: talent_path(@conn, :show_page, @current_user.id), method: :get,
		      class: "btn btn-default",
		      form: [class: "navbar-form navbar-right"] %></li>
	      <li role="separator" class="divider"></li>
	      <li><%= button "Log out", to: session_path(@conn, :logout),
		      class: "btn btn-default",
		      form: [class: "navbar-form navbar-right"] %></li>
	      <!--   </ul> -->
	      <!-- </li> -->
	      <% else %>
	      <li><%= button "Sign up", to: talent_path(@conn, :signup_page), method: :get,
		      class: "btn btn-default",
		      form: [class: "navbar-form navbar-right"] %></li>
	      <li><%= button "Log in", to: session_path(@conn, :login_page), method: :get,
		      class: "btn btn-default",
		      form: [class: "navbar-form navbar-right"] %></li>
	      <% end %>
	    </ul>
	  </div><!-- .navbar-collapse -->
	</nav>
	<!-- <div class="clear"></div> -->
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
	<%= render @view_module, @view_template, assigns %>
      </main>

      <!-- <script -->
      <!--    src="https://code.jquery.com/jquery-1.12.4.min.js" -->
      <!--    integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" -->
      <!--    crossorigin="anonymous"></script> -->

    </div> <!-- .container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>var App = require("web/static/js/app.js").App;</script>
  </body>
</html>

web/templates/layout/talent_app.html.eex
<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns:"http://www.w3.org/1999/xhtml">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Language" content="en">
    <meta name="google-site-verification" content="ClBh2WH0Zx_Cf8ixkCb67Oe2r5zaAcTKj9uLe39MWtw" />
    <meta name="google" content="notranslate">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>UNU</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">

      <main role="main">
	<%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- .container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>
      var App = require("web/static/js/app.js").App;
      App.register('<%= @view_template %>', document);
    </script>
  </body>
</html>